sudo: required
services:
  - docker

before_install:
  - docker build -t chilkuris/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run chilkuris/react-test npm run test -- --coverage

after_success:
  - docker build -t chilkuris/multi-client ./client
  - docker build -t chilkuris/multi-nginx ./nginx
  - docker built -t chilkuris/multi-server ./server
  - docker build -t chilkuris/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chilkuris/multi-client
  - docker push chilkuris/multi-nginx
  - docker push chilkuris/multi-server
  - docker push chilkuris/multi-worker
